Clean up typography on job descriptions
canonical-web-and-design/canonical.com pull request #343
Opened 2021-02-08 15:47 UTC by barrymcgee

## Done

Clean up typography on job descriptions by removing inline styles and empty paragraphs.

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8002/
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Click through different job descriptions
- Ensure typography is consistent

2021-02-08 15:47 UTC, webteam-app commented
Demo starting at https://canonical-com-343.demos.haus

2021-02-08 16:20 UTC, clagom commented
lgtm @barrymcgee thanks

2021-02-09 16:00 UTC, anthonydillon requested changes
Suggestion when resetting the headings.

2021-02-09 16:02 UTC, anthonydillon commented
Works well in the QA :+1:

2021-02-09 18:54 UTC, barrymcgee commented on static/sass/styles.scss
> +  }
Ok, done!

2021-02-09 21:48 UTC, anthonydillon approved these changes
LGTM :+1:

2021-02-09 21:48 UTC, merged