WIP - Update search result
canonical-web-and-design/canonical.com pull request #575
Opened 2022-07-18 13:29 UTC by minkyngkm

## Done

[List of work items including drive-bys]

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8002/
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- [List additional steps to QA the new features or prove the bug has been resolved]

## Issue / Card

Fixes #

## Screenshots

[if relevant, include a screenshot]

2022-07-18 13:29 UTC, webteam-app commented
Demo starting at https://canonical-com-575.demos.haus

2022-07-20 16:04 UTC, sowasred2012 requested changes
This looks good, but doesn't address a point @anthonydillon made in the previous PR - if there are no results, we should inform the user, like we do on live.

See:
https://canonical.com/careers/finance?filter=home-based&location=all#available-roles
vs
https://canonical-com-575.demos.haus/careers/all?search=fast

2022-07-21 05:46 UTC, minkyngkm commented
Thanks @sowasred2012. I forgot about that. It's fixed now 👍

2022-07-21 08:22 UTC, sowasred2012 commented on templates/careers/base.html
> -  <script src="{{ versioned_static('js/modules/fuse/fuse.js') }}"></script>
Not sure I understand why this was moved to base_index, won't that mean this script will be loaded on pages that don't use fuse?

2022-07-21 09:07 UTC, sowasred2012 approved these changes
Nice! LGTM

2022-07-21 10:43 UTC, merged